version: "3.9"
services:
  api:
    build: ./test-api
    ports:
      - "3000:3000"
  scheduler:
    build: ./scheduler
    depends_on:
      - "redis"
  handler:
    build: ./handler
    depends_on:
      - "redis"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"